# Generated by Django 5.2.17 on 2026-10-02 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_entitydefinition_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitydefinition',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='entitydefinition',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='entitydefinition',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='entityrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entityrecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_entity_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entityrecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
