# Generated by Django 5.2.17 on 2026-10-03 01:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_entitydefinition_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('relationship_type', models.CharField(choices=[('many_to_one', 'Many to One'), ('one_to_one', 'One to One'), ('many_to_many', 'Many to Many')], default='many_to_one', max_length=30)),
                ('required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='core.business')),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='core.entitydefinition')),
                ('target_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='core.entitydefinition')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['business', 'is_active'], name='core_relati_busines_2a1b59_idx'), models.Index(fields=['source_entity', 'is_active'], name='core_relati_source__b6075a_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_entity', 'slug'), name='unique_source_relationship_slug')],
            },
        ),
    ]
