# Generated by Django 5.2.17 on 2026-10-03 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_workflowdefinition_workflowstep_workflowinstance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('started', 'Started'), ('transitioned', 'Transitioned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_from_entries', to='core.workflowstep')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.workflowinstance')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_history_entries', to=settings.AUTH_USER_MODEL)),
                ('to_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to_entries', to='core.workflowstep')),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='core.workflowtransition')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['instance', 'created_at'], name='core_workfl_instanc_201ba0_idx')],
            },
        ),
    ]
