# Generated by Django 5.2.17 on 2026-10-03 23:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_workflowhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_slug', models.CharField(max_length=160)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('greater_than', 'Greater Than'), ('greater_than_or_equal', 'Greater Than or Equal'), ('less_than', 'Less Than'), ('less_than_or_equal', 'Less Than or Equal'), ('contains', 'Contains'), ('is_true', 'Is True'), ('is_false', 'Is False')], max_length=40)),
                ('value', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='core.workflowtransition')),
            ],
            options={
                'ordering': ('field_slug', 'created_at'),
                'indexes': [models.Index(fields=['transition', 'is_active'], name='core_workfl_transit_635cfa_idx')],
            },
        ),
    ]
