# Generated by Django 5.2.17 on 2026-10-03 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_workflowcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('action_type', models.CharField(choices=[('audit', 'Audit'), ('notification', 'Notification'), ('webhook', 'Webhook'), ('update_record', 'Update Record')], max_length=40)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.workflowtransition')),
            ],
            options={
                'ordering': ('position', 'created_at'),
                'indexes': [models.Index(fields=['transition', 'is_active'], name='core_workfl_transit_99f5e9_idx')],
            },
        ),
    ]
