# Generated by Django 5.2.17 on 2026-10-04 01:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_workflowaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('event_type', models.CharField(choices=[('record_created', 'Record Created'), ('record_updated', 'Record Updated'), ('record_deleted', 'Record Deleted')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='core.workflowdefinition')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['workflow', 'is_active'], name='core_workfl_workflo_5fc8e5_idx'), models.Index(fields=['event_type', 'is_active'], name='core_workfl_event_t_43bc0a_idx')],
            },
        ),
    ]
