# Generated by Django 5.2.17 on 2026-10-04 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_workflowtrigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowActionExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('workflow_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='core.workflowaction')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_executions', to='core.workflowinstance')),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['workflow_instance', 'started_at'], name='core_workfl_workflo_fae694_idx'), models.Index(fields=['workflow_action', 'started_at'], name='core_workfl_workflo_020e14_idx'), models.Index(fields=['status', 'started_at'], name='core_workfl_status_dfe65f_idx')],
            },
        ),
    ]
