# Generated by Django 5.2.17 on 2026-10-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_workflowactionexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowactionexecution',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowactionexecution',
            name='max_retries',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='workflowactionexecution',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowactionexecution',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
