# Generated by Django 5.2.17 on 2026-10-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_workflowactionexecution_last_retry_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowactionexecution',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowactionexecution',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowactionexecution',
            name='worker_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='workflowactionexecution',
            index=models.Index(fields=['status', 'queued_at'], name='core_workfl_status_5f6086_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowactionexecution',
            index=models.Index(fields=['status', 'next_retry_at'], name='core_workfl_status_f341c2_idx'),
        ),
    ]
